### ISSUE TITLE
Too many signs

### ISSUE THREAD

**Issue by BenGonGar** [lexcia98/rge#3]
**Describe the bug**
A single shop has 3 signposts

**To Reproduce**

1. Go to Winterhold look at birdnas oddments
2. Do the tango?

**Expected behavior**
The shop should only have 1 Sign.

**Screenshots**
![SkyrimSE 2021-08-05 13-34-58](https://user-images.githubusercontent.com/88422225/128395740-50328a7f-9c37-40be-a1cd-2278ebfbc779.png)
![SkyrimSE 2021-08-05 13-35-00](https://user-images.githubusercontent.com/88422225/128395756-ed714702-ced8-40a0-86fb-ecadc80a11e3.png)
![SkyrimSE 2021-08-05 13-35-02](https://user-images.githubusercontent.com/88422225/128395787-2bb58e9b-6711-4b4a-be71-c3dcca87d30a.png)

**Modlist version**
2.2.5.2

**Did you add any additional mods?**
Yes, MXAO on re-shade.

**Comment by lexcia98** [comment]
New update has seen this blatant disregard for advertising etiquette addressed. Should be out in a day or 2, time permitting.
