### ISSUE TITLE
Wall plant.

### ISSUE THREAD

**Issue by BenGonGar** [lexcia98/rge#4]
**Describe the bug**
A nice wall plant that violates many rules.

**To Reproduce**

1. Go to Winterhold look at oddments shop wall.
2. Do an existential crisis since gravity seems to be a suggestion and nutrition.

**Expected behavior**
Plants should grow on dirt not shop walls.

**Screenshots**
![SkyrimSE 2021-08-05 13-39-14](https://user-images.githubusercontent.com/88422225/128396257-4f840220-b3b6-4db0-92df-61394ccbe7a3.png)

Modlist version
2.2.5.2

Did you add any additional mods?
Yes, MXAO on re-shade.

**Comment by lexcia98** [comment]
While the plant's tenacity is appreciated, its hatred of gravity is not.  Removed in upcoming update.
