### ISSUE TITLE
Winterhold Shenanigans

### ISSUE THREAD

**Issue by BenGonGar** [lexcia98/rge#5]
**Describe the bug**
A stuck banner and a floating lantern.

**To Reproduce**

1. Go to Winterhold entrance.
2. Do wonder is the mages there are breaking reality.

**Expected behavior**
a non-suck inside a wall flag and a non-floating lantern.

**Screenshots**
![SkyrimSE 2021-08-05 13-45-41](https://user-images.githubusercontent.com/88422225/128396999-a9fbf4d2-9137-4a80-b5a1-58c29ca3b16c.png)
![SkyrimSE 2021-08-05 13-45-31](https://user-images.githubusercontent.com/88422225/128397021-a727e5c6-a3e4-4d16-874f-2132e70f20c0.png)

Modlist version
2.2.5.2

Did you add any additional mods?
Yes, MXAO on re-shade.

**Comment by lexcia98** [comment]
Removed for now, will try to move to better places once I have time and a better handle on the creation kit. Thanks Zheyken!
