### ISSUE TITLE
2 Mods can't be downloaded because they no longer seem to exist on Nexus.

### ISSUE THREAD

**Issue by jojadu** [lexcia98/rge#6]
Title pretty much sums it up:

314.85 - Unable to download ESO Skyshards-6331-2-2-1-1622841803.7z (NexusDownloader+State|SkyrimSpecialEdition|6331|207265)
314.85 - Unable to download Whistling Mine-367-2-0-6-1557535371.7z (NexusDownloader+State|SkyrimSpecialEdition|367|91673)
314.85 - Cannot continue, was unable to download one or more archives

I'm new to Wabbajack, but it seems there is no way forward with any missing mods. Is there anything I can do?

**Comment by lexcia98** [comment]
Solved in later updates.
